### PR TITLE
mod: re-join require sections, run mod tidy

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Comment by mvdan** [comment]
FYI @jordipainan this happened in https://github.com/vocdoni/vocdoni-node/commit/ed5fb167e1a658b63318ec13b06fd65f14ca1aa5#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6, do you remember how it happened?

**Comment by jordipainan** [comment]
> FYI @jordipainan this happened in [ed5fb16#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6](https://github.com/vocdoni/vocdoni-node/commit/ed5fb167e1a658b63318ec13b06fd65f14ca1aa5#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6), do you remember how it happened?

hey dani thank you! probably I fkd up when solving conflicts, sorry for that

**Review by jordipainan — APPROVED** [review]

**Comment by mvdan** [comment]
Rebased since some CI changes were made

**Comment by mvdan** [comment]
FYI @chilcano your recent change with pull_request_target means that we run each job twice when testing PRs.

image

**Comment by mvdan** [comment]
Now it's stuck because it requires "job_go_tests" to pass, which doesn't apear to be running?

**Comment by chilcano** [comment]
Thanks @mvdan for the heads up.
I made these changes because for any reason Pull Request from forked repo like yours are being ignored and skipped by GitHub actions. I removed `if: github.event_name == 'push'` and added  `on: [..., pull_request_target]`.
In other words:
1. a regular commit generates a `push` event that triggers github workflow.
2. a regular PR generates `pull_request` event that triggers github workflow.
3. a PR coming from forked repo generates a `pull_request_target` event that triggers github workflow.

Seems that (2) and (3) is happening at the same time when PR is raised from forked repo. I'm going to debug this process and will back to you.
Please, anything, just let me know.
Regards

**Pull request merged**
