### PR TITLE
feat(ci): adds scan-vulns-deps as github workflow

### PR DESCRIPTION
**Pull request by chilcano**
Trivy has been added as SCA tool to scan for vulnerabilities in the Repository (libraries and 3rd party dependencies) and Docker image.
Additionally, Trivy look for misconfiguration in Dockerfiles and leaked secrets in repo and docker img.

### CODE REVIEW

**Comment by p4u** [comment]
wow, nice Job.
But the PR should not go to "dev" but to "master".

**Comment by p4u** [comment]
wow, nice Job.
But the PR should not go to "dev" but to "master".

**Comment by p4u** [comment]
ping @chilcano

**Comment by p4u** [comment]
@chilcano can you clarify when this task is executed? I'd prefer not to run it on every push, instead it would be nice to reduce its scope to something like only PR to master.

**Comment by chilcano** [comment]
> @chilcano can you clarify when this task is executed? I'd prefer not to run it on every push, instead it would be nice to reduce its scope to something like only PR to master.

Hi @p4u 
This GH workflow is triggered in any push to long-lived and feature (`DOPS-xyz`) branches.

```yml
name: scan-vulns-deps 

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - stage
      - master
      - apiv2
      - 'release-*'
      - 'DOPS-*'
...
``` 

Yes, reducing the scope to PR to master is an option, however I think to be consistent, scanning of vulns should be integrated in all branches with some differences. To be consistent, we should have 2 GH workflows.

For example:

* Workflow 1 => If this a PR (in Main, Stg, Release) => Implement a Control Gate (approve the PR if Total vulns < 20% and Total vulns = LOW ).

* Workflow 2 => If this is PUSH in feature branch and Dev => Scan and report vulns.

Although, enabling this workflow is not harmful since this is executed in GH standard runner and separate GH workflow also It doesn't block or affect the performance of other workflows.

I can do now is tweaking this current workflow to trigger with a PUSH in any branch. It only will scan and generate reports. Once reduced the number of vulns and embraced the fixing vulns process, I can implement the Control Gate above mentioned only available for PR in long-lived branches such as main, release, stg, etc.

What do you think?.

**Comment by p4u** [comment]
All commits (except very few exceptional hotfixes) go through the master branch. The other branches are just used as snapshots (with minor naming and configuration tweaks) for Master. 

Thus having this on PR to Master should cover 99% of the cases.

**Comment by p4u** [comment]
I cannot approve btw since I'm not set as reviewer for this PR. Only @emmdim can do it.

**Comment by chilcano** [comment]
> All commits (except very few exceptional hotfixes) go through the master branch. The other branches are just used as snapshots (with minor naming and configuration tweaks) for Master.
> 
> Thus having this on PR to Master should cover 99% of the cases.

With this the workflow only is triggered by **open PR** event to master, which is fine. The bad part is that the Developer will be pushing changes blindly without knowing if their changes have vulnerabilities. That is why I've configured it to be triggered by **PUSH** event on feature branches and long-lived branches such as master, stage, ...

That is the reason I've configured the workflow with this:
```yaml
name: scan-vulns-deps 

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - stage
      - master
      - apiv2
      - 'release-*'
      - 'DOPS-*'

jobs:

  build-and-deploy:
....
```

However, if the workflow is triggered by both events (PUSH and PR), the build time will take 2 times of regular duration and in the PR you will have a list of duplicated jobs, in this case, one for PR and another one for PUSH. For example, this config will trigger 2 times:

```yaml
name: scan-vulns-deps 

on:
  workflow_dispatch:
  push:
    branches:
      - dev
      - stage
      - apiv2
      - 'release-*'
      - 'DOPS-*'
  pull_request:
    branches:
      - master
jobs:

  build-and-deploy:
....
```

Comments are welcome.
Regards.

**Comment by p4u** [comment]
@chilcano two comments:

1. Could you rebase with current master?

2. You can remove `apiv2` branch workflow, it is deprecated and should be removed

**Comment by chilcano** [comment]
Hi @p4u 

1. rebase done
2. apiv2 removed from workflow

Regards.

**Comment by p4u** [comment]
@chilcano no se que ha pasado en el rebase, pero el histórico no parece correcto.

En teoria, algo así deberia funcionar.
```
git merge --ff origin/master
git rebase origin/master
```

He creado un nuevo PR haciendo cherry-pick de tu commit y partiendo de master actual. Si quieres cerramos este y hacemos merge del otro.

https://github.com/vocdoni/vocdoni-node/pull/969

Saludos.

**Pull request closed without merging**
