### PR TITLE
vochain/scrutinizer: fix 0.4% of entity IDs with sqlite

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

Updates #414.

### CODE REVIEW

**Comment by mvdan** [comment]
I'm not closing #414 yet, because some of the recent panics do not include an entity_id starting with a null byte. So there might be another bug to fix.

**Comment by mvdan** [comment]
Also, sqlc is actively working on native sqlite support, so hopefully we'll be able to remove these workarounds soon. For the time being, they're not too painful.

**Comment by mvdan** [comment]
I should note that I'm not sure whether our real environments produce random entity IDs, but even if they don't, it's still better to plug this trap.

**Review by NateWilliams2 — APPROVED** [review]
LGTM, I think there is actually a chance of this occurring in real behavior.

**Comment by mvdan** [comment]
We'll see if dev or staging still see warnings after this.

**Pull request merged**
