### PR TITLE
vochain/scrutinizer: close the scrutinizer when tests finish

### LINKED ISSUE #616: ci: go-tests sometimes fail with "TempDir RemoveAll cleanup: [...] directory not empty"
for example:
https://github.com/vocdoni/vocdoni-node/actions/runs/3137078090/jobs/5094795954
```
--- FAIL: TestEntityList (12.05s)
    scrutinizer_test.go:68: list is empty
    scrutinizer_test.go:68: list is empty
    scrutinizer_test.go:68: list is empty
    testing.go:1090: TempDir RemoveAll cleanup: unlinkat /tmp/TestEntityList3644702761: directory not empty
FAIL
coverage: 57.1% of statements
FAIL	go.vocdoni.io/dvote/vochain/scrutinizer	37.815s
```

this is due to some goroutine writing to a tempfile, after the calling function returned. being a race, it only happens once in a while.
see https://github.com/golang/go/issues/43547
maybe @mvdan has a trivial solution?

### LINKED ISSUE #617: ci: scrutinizer test sometimes times out
for example
https://github.com/vocdoni/vocdoni-node/actions/runs/3137078872/jobs/5094797704#step:5:393
```
panic: test timed out after 1m0s

goroutine 252826 [running]:
testing.(*M).startAlarm.func1()
	/usr/local/go/src/testing/testing.go:2029 +0x8e
created by time.goFunc
	/usr/local/go/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive]:
testing.(*T).Run(0xc0004d1380, {0x159d2f3?, 0x52e245?}, 0x18b1ae8)
	/usr/local/go/src/testing/testing.go:1487 +0x37a
testing.runTests.func1(0xc0004d1380?)
	/usr/local/go/src/testing/testing.go:1839 +0x6e
testing.tRunner(0xc0004d1380, 0xc0001fbca0)
	/usr/local/go/src/testing/testing.go:1439 +0x102
testing.runTests(0xc0006be280?, {0x2322380, 0xd, 0xd}, {0x7f2725902a68?, 0x40?, 0x23e3c40?})
	/usr/local/go/src/testing/testing.go:1837 +0x457
testing.(*M).Run(0xc0006be280)
	/usr/local/go/src/testing/testing.go:1719 +0x5d9
main.main()
	_testmain.go:133 +0x255

[...]

goroutine 248826 [sleep]:
time.Sleep(0x12a05f200)
	/usr/local/go/src/runtime/time.go:194 +0x12e
go.vocdoni.io/dvote/vochain/scrutinizer.(*Scrutinizer).computePendingProcesses(0xc01d398780, 0xebe2780?)
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/process.go:360 +0x77
created by go.vocdoni.io/dvote/vochain/scrutinizer.(*Scrutinizer).Commit
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/scrutinizer.go:471 +0xf25
FAIL	go.vocdoni.io/dvote/vochain/scrutinizer	60.569s
```

another example (basically same output):
https://github.com/vocdoni/vocdoni-node/actions/runs/3137079128/jobs/5094798365#step:5:378

both runs happened in the slowest build server (ci2), this same server sometimes manages to run the test successfully. maybe the difference is whether is under load or not. but anyway we should either dig into this or at the very minimum increase the timeout of this test, so it's not flaky anymore.

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

Fixes #616.
Fixes #617.

### CODE REVIEW

**Comment by altergui** [comment]
nice!
being a race condition, i'll spam the CI server with 10 jobs and see if none of them fail

**Comment by altergui** [comment]
https://github.com/vocdoni/vocdoni-node/actions/runs/3198761522/jobs/5223702308#step:5:425
```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: Unclosed iterator at time of Txn.Discard.
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x983feb]

goroutine 53946 [running]:
github.com/dgraph-io/badger/v3.(*Txn).Discard(0x203006?)
	/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.2/txn.go:523 +0x9e
panic({0x13e69e0, 0x2302a60})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/dgraph-io/badger/v3.(*memTable).IncrRef(...)
	/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.2/memtable.go:231
github.com/dgraph-io/badger/v3.(*DB).getMemTables(0xc010710000)
	/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.2/db.go:696 +0x12b
github.com/dgraph-io/badger/v3.(*Txn).NewIterator(0xc01b690c80, {0x64, 0x1, 0x0, 0x0, 0x0, 0x0, {0x0, 0x0, 0x0}, ...})
	/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.2/iterator.go:485 +0x87
github.com/timshannon/badgerhold/v3.(*Store).newIterator(0xc0107004e0, 0xc01b690c80, {0x12fc6db, 0x7}, 0xc01b6b7400, 0x0)
	/go/pkg/mod/github.com/vocdoni/badgerhold/v3@v3.0.0-20210514115050-2d704df3456f/index.go:189 +0xf2
github.com/timshannon/badgerhold/v3.(*Store).runQuery(0xc0107004e0, 0xc01b690c80, {0x13c3ca0, 0xc01a5e63c0}, 0xc01b6b7400, {0x0, 0x0, 0x0}, 0x0, 0xc00078de30)
	/go/pkg/mod/github.com/vocdoni/badgerhold/v3@v3.0.0-20210514115050-2d704df3456f/query.go:582 +0x28a
github.com/timshannon/badgerhold/v3.(*Store).forEach(0xc00f68d680?, 0x420285?, 0xc0000ac690?, {0x138a020?, 0xc01b6a1800?})
	/go/pkg/mod/github.com/vocdoni/badgerhold/v3@v3.0.0-20210514115050-2d704df3456f/query.go:1097 +0x234
github.com/timshannon/badgerhold/v3.(*Store).TxForEach(...)
	/go/pkg/mod/github.com/vocdoni/badgerhold/v3@v3.0.0-20210514115050-2d704df3456f/get.go:121
github.com/timshannon/badgerhold/v3.(*Store).ForEach.func1(0xc010710000?)
	/go/pkg/mod/github.com/vocdoni/badgerhold/v3@v3.0.0-20210514115050-2d704df3456f/get.go:115 +0x2f
github.com/dgraph-io/badger/v3.(*DB).View(0x0?, 0xc00ce7c6f8)
	/go/pkg/mod/github.com/dgraph-io/badger/v3@v3.2103.2/txn.go:806 +0x9c
github.com/timshannon/badgerhold/v3.(*Store).ForEach(0x1598451?, 0x0?, {0x138a020?, 0xc01b6a1800?})
	/go/pkg/mod/github.com/vocdoni/badgerhold/v3@v3.0.0-20210514115050-2d704df3456f/get.go:114 +0x65
go.vocdoni.io/dvote/vochain/scrutinizer.(*Scrutinizer).computePendingProcesses(0xc00e5108c0, 0xf812c80?)
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/process.go:363 +0x2c5
created by go.vocdoni.io/dvote/vochain/scrutinizer.(*Scrutinizer).Commit
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/scrutinizer.go:484 +0xf25
FAIL	go.vocdoni.io/dvote/vochain/scrutinizer	17.053s
```

**Comment by mvdan** [comment]
Thanks, will look into it tomorrow.

**Comment by mvdan** [comment]
The problem is that the scrutinizer's Commit method spawns a couple of goroutines that continue using the DBs asynchronously. So when the tests advance a few blocks to mimic the real blockchain (which then commits those blocks), and the tests finishes shortly after, the test may then close the DBs before those async Commit goroutines have finished.

I'm talking about these two:

```
go s.indexNewTxs(s.newTxPool)

[...]

go s.computePendingProcesses(height)
```

This means that stopping the scrutinizer in a clean way is, currently, not possible. We only started spotting this problem because in this PR I'm trying to close the scrutinizer's DBs before we try to remove the entire temporary directory. The tests need to remove the temporary directories, as otherwise we "leak" files that pile up.

@p4u @jordipainan any ideas? I don't know why Commit is spawning goroutines.

**Comment by mvdan** [comment]
One possible solution would be for the scrutinizer's Close method to wait for all of its async goroutines to be finished. This would be a small refactor but I can't think of a simpler workaround, as long as we want to keep those async goroutines.

**Comment by altergui** [comment]
would a `time.Sleep(blockInterval)` avoid such a refactor? i know, horrible, but in this case maybe it's not worth the effort?

**Comment by mvdan** [comment]
No, because it's not guaranteed that the goroutines would finish within that interval. There's nothing stopping the goroutines from block 10 to still run when block 11 gets committed and processed.

**Comment by p4u** [comment]
Can we merge this @altergui @mvdan ?

**Comment by mvdan** [comment]
No, see my question in https://github.com/vocdoni/vocdoni-node/pull/626#issuecomment-1272513233.

**Comment by p4u** [comment]
> The problem is that the scrutinizer's Commit method spawns a couple of goroutines that continue using the DBs asynchronously. So when the tests advance a few blocks to mimic the real blockchain (which then commits those blocks), and the tests finishes shortly after, the test may then close the DBs before those async Commit goroutines have finished.
> 
> I'm talking about these two:
> 
> ```
> go s.indexNewTxs(s.newTxPool)
> 
> [...]
> 
> go s.computePendingProcesses(height)
> ```
> 
> This means that stopping the scrutinizer in a clean way is, currently, not possible. We only started spotting this problem because in this PR I'm trying to close the scrutinizer's DBs before we try to remove the entire temporary directory. The tests need to remove the temporary directories, as otherwise we "leak" files that pile up.
> 
> @p4u @jordipainan any ideas? I don't know why Commit is spawning goroutines.

The reason of launching these two functions async is because they are not modifying the blockchain state and they are costly operations so we don't want them to interfere in the the state construction. 

I would like to keep them async if possible. I imagine the only current solution is to use a context to propagate the Close(). A quick fix for the test might be a dirty time.Sleep(), I don't think this should usually take more than 1 or 2 seconds in the tests.

**Comment by p4u** [comment]
ping @mvdan

**Comment by mvdan** [comment]
I spent a bit of time thinking about how to fix this without more sleeps. The tests are already slow enough as they are :)

I first thought about a test-only solution, which would make the Commit goroutines _not_ be async when running the tests. But that didn't feel right - we shouldn't be testing different code than what runs in production.

Then I thought about a bigger refactor to properly attach lifetimes (cancellation and "done" signals) to all goroutines and method calls. However, since Commit is called via a callback in the App type, that was tricky and touched tons of files. So I gave up.

I ended up with a middle ground: modified the scrutinizer just enough so that it can be cancelled and shut down properly from the tests. We just have one sleep remaining - in WaitIdle, since it polls for the number of goroutines. That's not perfect, but it's OK for the tests.

**Comment by mvdan** [comment]
Hm, how did I not notice the hang? Looking again.

**Comment by p4u** [comment]
Great, that's a much better solution I'd have think about. 

We should ideally use contexts all over the code to avoid these situations, but that's something that would require quite effort. 

Thanks!

**Comment by p4u** [comment]
@altergui since you were involved in the discussion, please add your review

**Review by p4u — APPROVED** [review]

**Comment by mvdan** [comment]
Rebased, let me know what you think @altergui. If you hit a flake, see https://github.com/vocdoni/vocdoni-node/issues/642.

**Review by altergui — APPROVED** [review]
LGTM, in 10 runs no "TempDir RemoveAll cleanup" error

there was 1 timeout as in #617 
https://github.com/vocdoni/vocdoni-node/actions/runs/3361233088/jobs/5571374617#step:5:406

but i'd merge the current PR anyway

**Pull request merged**
