### PR TITLE
start_test.sh: refactor to make it more easily extensible

### PR DESCRIPTION
**Pull request by altergui**
given @NateWilliams2 and @jordipainan lost precious time fighting bash, here's a quick refactor of `start_test.sh` to make it more readable and easier to add new tests.

### CODE REVIEW

**Comment by jordipainan** [comment]
can't properly review, but the parts I understand are looking good :)

**Review by NateWilliams2 — APPROVED** [review]
Looks much more intuitive to me. thanks!!

**Comment by mvdan** [comment]
Hmm, compose-test failed in master after the merge, and it's failing for other PRs as well, like https://github.com/vocdoni/vocdoni-node/pull/494, with the same error. cc @vdo

**Comment by altergui** [comment]
it doesn't look related to this refactor
```
2022-02-24T15:09:59Z	FATAL	vochaintest/vochaintest.go:998	treasurer nonce expected to be 1 got 0
main.testTokenTransactions
	go.vocdoni.io/dvote/cmd/vochaintest/vochaintest.go:998
main.main
	go.vocdoni.io/dvote/cmd/vochaintest/vochaintest.go:160
runtime.main
	runtime/proc.go:255
	
```
but i'll have a look

**Comment by mvdan** [comment]
@jordipainan mentioned in our sync call that he's working on it :)

**Pull request merged**
