### PR TITLE
simplify our uses of LRU caches

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Comment by p4u** [comment]
So the LRU cache is not safe anymore? I'm not getting the full meaning of the comment.

**Comment by mvdan** [comment]
lru.Cache is safe for concurrent use, just like it was before.

**Comment by altergui** [comment]
sorry for closing this (it was automatic, github couldn't update the base branch), please reopen against `main`

**Comment by mvdan** [comment]
reopened as a new PR.

**Pull request closed without merging**
