### PR TITLE
Adding Fuji and Avax

### PR DESCRIPTION
**Pull request by maektwain**
This might fail in the CI and CD but if we quickly merge the other code PR on the proto, then it might not

Apart from this topic, I would like to know how we can help in terms of implementing a POS-based consensus like Avalanche or through the subnet.

Thanks

### CODE REVIEW

**Comment by p4u** [comment]
Protobuf merged. Now you should update the go.mod `go get go.vocdoni.io/proto@master`

**Comment by p4u** [comment]
I have cherry-pick your dvote-proto commit from release-1.2 to master btw

**Comment by maektwain** [comment]
> Protobuf merged. Now you should update the go.mod `go get go.vocdoni.io/proto@master`

Done

**Comment by p4u** [comment]
@jordipainan feel free to merge it yourself once you think it is ok :)

**Review by jordipainan — APPROVED** [review]

**Pull request merged**
