### PR TITLE
update to go 1.23.0

### PR DESCRIPTION
**Pull request by p4u**

### CODE REVIEW

**Comment by p4u** [comment]
Any glue why this is happening @altergui?

**Comment by altergui** [comment]
```
#16 0.063 go: go.mod requires go >= 1.23.0 (running go 1.22.6; GOTOOLCHAIN=local)
#16 ERROR: process "/bin/sh -c go mod download -x" did not complete successfully: exit code: 1
```
maybe something outdated at the runner? i'm taking a look

**Comment by altergui** [comment]
ok so wait, actually the failing job is the scan-vuln-deps that we seldom maintain, i'd bet there's some action that needs to be bumped (happened to me in the past). but maybe we could simply drop that action altogether, due to lack of maintenance.

**Comment by p4u** [comment]
I'd drop it @altergui

**Review by altergui — APPROVED** [review]

**Pull request merged**
