### PR TITLE
vochain/indexer: rewrite sqlc config to version 2

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Review by jordipainan — APPROVED** [review]
Merge before #700, so I can adapt changes made on it.

**Comment by mvdan** [comment]
Oops, I forgot your PR. Please merge yours first.

**Comment by jordipainan** [comment]
I prefer you to merge this first, as #759 was merged without waiting for #700. I'll make the changes on top of this.

**Comment by mvdan** [comment]
Alright. I'll make sure to not cause you more conflicts before your PR is merged.

**Pull request merged**
