### PR TITLE
Revert "Disable compose tests"

### PR DESCRIPTION
**Pull request by p4u**
This reverts commit 284701aac762f5728d118e9b1849d50a9d0e96c6.

### CODE REVIEW

**Comment by p4u** [comment]
We need to fix this @arnaucube @vdo ?

**Comment by p4u** [comment]
In local works for me... So its something with the CI environment or the github workflow configuration

**Comment by vdo** [comment]
This commit was supposed to be on the `ethless` branch only, to prevent integration tests that were failing, but it was merged to master with the rest.

**Comment by p4u** [comment]
> This commit was supposed to be on the `ethless` branch only, to prevent integration tests that were failing, but it was merged to master with the rest.

Yes, my bad.

**Pull request merged**
