### PR TITLE
tree/arbo: import from github.com/vocdoni/arbo with history

### PR DESCRIPTION
**Pull request by mvdan**
You should review the last two commits, made on top of the subtree merge.

(see commit messages - please do not squash)

### CODE REVIEW

**Review by arnaucube — APPROVED** [review]

**Comment by mvdan** [comment]
staticcheck should be green now.

**Comment by p4u** [comment]
@lucasmenendez be aware of this :)

**Comment by mvdan** [comment]
We also had agreed to do this almost exactly a year ago, but I guess I forgot to actually do it! https://github.com/vocdoni/vocdoni-node/issues/399#issuecomment-1022425360

**Comment by p4u** [comment]
Next, we should get rid of the `tree` package probably and use arbo directly.

**Review by p4u — APPROVED** [review]

**Pull request merged**
