### PR TITLE
vochain: AddProcess now returns error if process status is UNKNOWN

### PR DESCRIPTION
**Pull request by altergui**

### CODE REVIEW

**Comment by altergui** [comment]
fixes #687

**Comment by altergui** [comment]
actually i missed the comment about "A process can only be created in READY or PAUSED status."
i'll redo the PR, but first i'd love to have feedback if this is the right place to implement such checks

**Review by p4u — APPROVED** [review]
I think this change is state breaking, since some processes might be already created at UNKNOWN state. In this case you should upgrade the Development Genesis file to make the testnet blockchain auto-restart.

**Comment by p4u** [comment]
The check here looks good. But this will only be triggered when Commit()  It would be better to discard the transaction already on mempool's CheckTx(), that's in the transactions.go file NewProcessTxCheck() if I recall correctly.

**Review by p4u — CHANGES_REQUESTED** [review]
Let's apply this changes before approving.

**Comment by altergui** [comment]
perfect feedback @p4u :heart: 

rewritten from scratch, now check happens where it should (CheckTx) and fails on any state except READY or PAUSED
also dev genesis version is bumped

**Review by p4u — APPROVED** [review]

**Review by jordipainan — APPROVED** [review]

**Pull request merged**
