### PR TITLE
vochain/indexer: deduplicate more queries, tidy up count methods

### PR DESCRIPTION
**Pull request by mvdan**
(see commit messages - please do not squash)

### CODE REVIEW

**Comment by mvdan** [comment]
the swagger workflow is complaining about a token, @altergui?

**Comment by altergui** [comment]
> the swagger workflow is complaining about a token, @altergui?

you opened the PR from your private clone. i'll push a fix for the swagger workflow to be skipped in that case.

edit: actually disabled the trigger on pull_request altogether #1036

**Comment by mvdan** [comment]
gotcha. I've always sent PRs from a fork :) it's a public fork though, not private.

**Review by altergui — APPROVED** [review]
LGTM

**Pull request merged**
