### PR TITLE
census: add support for protobuf definition of weighted voting

### PR DESCRIPTION
**Pull request by jordipainan**

### CODE REVIEW

**Comment by jordipainan** [comment]
@p4u do you want to apply this commit directly to `dev` or do you want to apply this to `master` and then sync `dev` with `master` ? Thank you

**Comment by p4u** [comment]
This should go to master and then merged to dev

**Comment by p4u** [comment]
So I did the merges and so on. Thanks @jordipainan

**Comment by jordipainan** [comment]
thanks to you @p4u

**Pull request closed without merging**
