### PR TITLE
WIP: Tendermint 0.35

### PR DESCRIPTION
**Pull request by p4u**

### CODE REVIEW

**Comment by altergui** [comment]
So i dug into a problem that @p4u came across, namely a regression on peer exchange that prevents nodes from discovering each other (they only connect to Seeds aka BootstrapNodes)

and proposed a solution upstream
https://github.com/tendermint/tendermint/pull/7594

with this fix, the network works as expected running on tendermint 0.35

**Comment by p4u** [comment]
> So i dug into a problem that @p4u came across, namely a regression on peer exchange that prevents nodes from discovering each other (they only connect to Seeds aka BootstrapNodes)
> 
> and proposed a solution upstream [tendermint/tendermint#7594](https://github.com/tendermint/tendermint/pull/7594)
> 
> with this fix, the network works as expected running on tendermint 0.35

amazing catch @altergui !

**Comment by altergui** [comment]
my fix was merged upstream, in v0.35.x branch so i just pointed our go.mod to that (untagged) commit. when they tag a release in that branch (v0.35.1 i imagine) we can update our go.mod

**Comment by altergui** [comment]
i pushed a merge resolving conflicts with master, so that it's trivial to do a squash-rebase of all this

**Comment by altergui** [comment]
strangely, go-tests failed due to many race conditions in TestVocone
 https://github.com/vocdoni/vocdoni-node/runs/4888988673?check_suite_focus=true#step:4:436 

but i couldn't reproduce the FAIL, tried both on my laptop and on a build server. Re-running the github job also passed successfully.
looking at the original logs, looks like something related to `arbo` but i'm not really sure. i'll not debug this further, basically because i can't reproduce it :confused:

**Comment by p4u** [comment]
> strangely, go-tests failed due to many race conditions in TestVocone https://github.com/vocdoni/vocdoni-node/runs/4888988673?check_suite_focus=true#step:4:436
> 
> but i couldn't reproduce the FAIL, tried both on my laptop and on a build server. Re-running the github job also passed successfully. looking at the original logs, looks like something related to `arbo` but i'm not really sure. i'll not debug this further, basically because i can't reproduce it confused

@mvdan something to add here?

**Comment by p4u** [comment]
@altergui I'm not sure why there are so many conflicts since we merged https://github.com/vocdoni/vocdoni-node/pull/437

The main commit introduced by that PR was already included here :/

Probably changing the strategy to a Merge-commit would remove the conflicts? I think in that case it is acceptable to add a merge-commit. Can you check it @altergui ?

**Comment by altergui** [comment]
all the conflicts were due to me merging f/fix_signatures (which was since then merged into master, albeit with different commit id). i solved it with git.

there's only a single real conflict, which i'm not sure how to solve: in tendermint-0.35 the whole "Wait for Vochain to be ready" is gone. on the contrary, in master, the last 4 lines (`if signer`) were added.
should i keep just the last 4 lines, or the whole block?

```diff
(tendermint-0.35!) $ git diff
diff --cc cmd/dvotenode/dvotenode.go
index bfce9464,6d324d9b..00000000
--- a/cmd/dvotenode/dvotenode.go
+++ b/cmd/dvotenode/dvotenode.go
@@@ -524,10 -524,23 +524,26 @@@ func main() 
                        log.Fatal(err)
                }
                defer func() {
 -                      vochainApp.Node.Stop()
 -                      vochainApp.Node.Wait()
 +                      vochainApp.Service.Stop()
 +                      vochainApp.Service.Wait()
                }()
  
++<<<<<<< HEAD
++=======
+               // Wait for Vochain to be ready
+               var h, hPrev uint32
+               for vochainApp.Node == nil {
+                       hPrev = h
+                       time.Sleep(time.Second * 10)
+                       h = vochainApp.Height()
+                       log.Infof("[vochain info] replaying height %d at %d blocks/s",
+                               h, (h-hPrev)/5)
+               }
+               if signer != nil {
+                       signer.VocdoniChainID = vochainApp.ChainID()
+               }
+               log.Infof("vochain chainID %s", vochainApp.ChainID())
++>>>>>>> master
        }
  
        //
```

**Comment by altergui** [comment]
the history is extremely dirty tho. i'll rebase it and clean it up, looking at the history i think it makes sense to squash everything into a single commit

**Comment by altergui** [comment]
there you go, nicely squashed into a single commit with changelog

the original branch is left at fc1a8053008107eccf08f3f023e5c0325c83fe37

**Comment by p4u** [comment]
> there you go, nicely squashed into a single commit with changelog
> 
> the original branch is left at [fc1a805](https://github.com/vocdoni/vocdoni-node/commit/fc1a8053008107eccf08f3f023e5c0325c83fe37)

great

**Comment by altergui** [comment]
my upstream fix was included in release v0.35.1 :partying_face: 
so i just updated `go.mod` to pull that release , yay!

**Comment by p4u** [comment]
Congratulations to all participants of this big upgrade! @mvdan @altergui

**Pull request merged**
