### PR TITLE
update ipfs

### PR DESCRIPTION
**Pull request by mvdan**
(see commit messages - please do not squash)

### CODE REVIEW

**Comment by p4u** [comment]
Can you fix the tests @mvdan ?

**Comment by mvdan** [comment]
It looks like updating cometbft breaks something:

> 2024-08-19T22:31:45.5197948Z testsuite_10461785872-seed-1         | [90m2024-08-19T22:22:53.074Z[0m [1m[31mERR[0m[0m comet: MConnection panicked [36merr=[0m"log line with invalid chars: \"\\x1b[90m10:22PM\\x1b[0m \\x1b[1m\\x1b[31mERR\\x1b[0m\\x1b[0m comet: tx already received from peer \\x1b[36msender=\\x1b[0mcb6a9612b39147cfc40e7514b334139004b7bf17 \\x1b[36mtx=\\x1b[0m\\\"W�:��2�{ڋUn-:�ы��ؖZWS��E]iE-\\\\x02\\\"\\n\"" [36mstack=[0m"goroutine 105 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x67\ngithub.com/cometbft/cometbft/p2p/conn.(*MConnection)._recover(0xc007d74000)\n\tgithub.com/cometbft/cometbft@v1.0.0-rc1/p2p/conn/connection.go:341 +0x58\npanic({0x4f06760?, 0xc007a91400?})\n\truntime/panic.go:770 +0x132\ngo.vocdoni.io/dvote/log.(*invalidCharChecker).Write(0x0?, {0xc0065d1180, 0xc8, 0x380})\n\tgo.vocdoni.io/dvote/log/log.go:85 +0x145\nbytes.(*Buffer).WriteTo(0xc0099303c0, {0x607f220, 0x8b294e0})\n\tbytes/buffer.go:261 +0x122\ngithub.com/rs/zerolog.ConsoleWriter.Write({{0x607f220, 0x8b294e0}, 0x0, {0x0, 0x0}, {0xc009c88540, 0x4, 0x4}, {0x0, 0x0, ...}, ...}, ...)\n\tgithub.com/rs/zerolog@v1.31.0/console.go:145 +0x9be\ngithub.com/rs/zerolog.LevelWriterAdapter.WriteLevel(...)\n\tgithub.com/rs/zerolog@v1.31.0/writer.go:27\ngithub.com/rs/zerolog.multiLevelWriter.WriteLevel({{0xc000a8f500?, 0x69?, 0x280992dd15?}}, 0x3, {0xc0065ac200, 0xe6, 0x1f4})\n\tgithub.com/rs/zerolog@v1.31.0/writer.go:80 +0xea\ngithub.com/rs/zerolog.(*Event).write(0xc00094e070)\n\tgithub.com/rs/zerolog@v1.31.0/event.go:80 +0x2b3\ngithub.com/rs/zerolog.(*Event).msg(0xc00094e070, {0xc00a387560, 0x24})\n\tgithub.com/rs/zerolog@v1.31.0/event.go:151 +0x43a\ngithub.com/rs/zerolog.(*Event).Msg(...)\n\tgithub.com/rs/zerolog@v1.31.0/event.go:110\ngo.vocdoni.io/dvote/log.(*CometLogger).Error(0xc0008b3560, {0x5566c9d, 0x1d}, {0xc009c88480, 0x4, 0x4})\n\tgo.vocdoni.io/dvote/log/comet.go:47 +0x28e\ngithub.com/cometbft/cometbft/mempool.(*CListMempool).CheckTx(0xc0050300c0, {0xc0065c8dc0, 0x130, 0x130}, {0xc0006315c0, 0x28})\n\tgithub.com/cometbft/cometbft@v1.0.0-rc1/mempool/clist_mempool.go:277 +0x6a2\ngithub.com/cometbft/cometbft/mempool.(*Reactor).Receive(0xc000a4a580, {{0x60d7d08, 0xc007d6bd40}, {0x60953d0, 0xc00a313758}, 0x30})\n\tgithub.com/cometbft/cometbft@v1.0.0-rc1/mempool/reactor.go:155 +0xa59\ngithub.com/cometbft/cometbft/p2p.createMConnection.func1(0x30, {0xc007d76000, 0x136, 0x1000})\n\tgithub.com/cometbft/cometbft@v1.0.0-rc1/p2p/peer.go:429 +0x65b\ngithub.com/cometbft/cometbft/p2p/conn.(*MConnection).recvRoutine(0xc007d74000)\n\tgithub.com/cometbft/cometbft@v1.0.0-rc1/p2p/conn/connection.go:671 +0x992\ncreated by github.com/cometbft/cometbft/p2p/conn.(*MConnection).OnStart in goroutine 219\n\tgithub.com/cometbft/cometbft@v1.0.0-rc1/p2p/conn/connection.go:238 +0x3dd\n"

(very mangled panic, but you see the original error "comet: tx already received from peer")

I will undo the cometbft update and keep the ipfs update.

**Comment by mvdan** [comment]
Green now. We can try with cometbft separately.

**Comment by altergui** [comment]
> (very mangled panic, but you see the original error "comet: tx already received from peer")

in fact it looks like our "log encoding issues detector" found a log line with encoding issues from comet (because tx= is not hex, likely a fmt.Sprintf `%s` vs `%x`) and panics because CI is run with LOG_PANIC_ON_INVALIDCHARS

either we fix that encoding upstream :eyes: or we disable our check

**Review by p4u — APPROVED** [review]

**Comment by p4u** [comment]
Created new issue for upgrading CometBFT https://github.com/vocdoni/vocdoni-node/issues/1378

**Pull request merged**
