### PR TITLE
f/optimistic provide

### LINKED ISSUE #989: Improved Performance in go-libp2p-kad-dht: New Feature Reduces PUT/Provide Latencies to <1s
Hi vocdoni Devs,

This is Dennis from Protocol Labs. I wanted to inform you about an exciting update regarding the [`go-libp2p-kad-dht`](https://github.com/libp2p/go-libp2p-kad-dht) implementation, which I believe you are currently using (at least indirectly via libipfs/boxo?). As part of our continuous efforts to enhance performance, we have introduced a new experimental feature that significantly improves the PUT/Provide latencies.

Previously, the DHT's PUT performance was known to be rather sluggish, often taking more than 10 seconds or even minutes. However, with the latest release of `go-libp2p-kad-dht` >v0.23.0, we have introduced a feature called "Optimistic Provide" [[Kubo documentation](https://github.com/ipfs/kubo/blob/master/docs/experimental-features.md#optimistic-provide)]. This feature has demonstrated great results, bringing the latencies down to less than 1 second in the 50th percentile and less than 1.4 seconds in the 90th percentile.

While I'm unaware of the specific requirements of your use case or whether the previous latencies posed any challenges for you, I wanted to ensure that you are aware of this improvement.

If you have any questions or would like more information about this new feature, please don't hesitate to reach out.

Cheers,
Dennis

### PR DESCRIPTION
**Pull request by altergui**
fix #989

### CODE REVIEW

**Comment by p4u** [comment]
fix the check please @altergui

**Comment by dennis-tra** [comment]
Great that you're taking the time to check this out!

I'm curious how your experience is. Quick question, are you using the IPFS DHT, another bigger DHT network, or a separate own one?

**Comment by p4u** [comment]
> Great that you're taking the time to check this out!
> 
> I'm curious how your experience is. Quick question, are you using the IPFS DHT, another bigger DHT network, or a separate own one?

We are using IPFS DHT.

**Comment by p4u** [comment]
We are not logging any metric regarding the latency on the DHT node discovery.

Before merging this experimental feature, it would be great to add some ipfs-connect metrics to Prometheus @altergui 

Feel free to comment and to discard this idea.

**Comment by dennis-tra** [comment]
When you get around adding metrics from before and after this change it would be great if you shared them with us. We would be interested in your experience with that feature 👍

**Comment by altergui** [comment]
sorry for taking so long, finally merged the stats in #1090 today
we'll collect current data (without optimistic provide) for a week, then merge this PR to enable optimistic provide, and report any differences

**Comment by dennis-tra** [comment]
Great, thanks for the ping! Looking forward to the results 👍

**Comment by dennis-tra** [comment]
From your linked PR #1090 I saw that you added a new metric with the help text: "The time it takes FindPeers to discover peers".

Just to clarify: Instead of improving the GET performance in the DHT, Optimistic Provide is designed to accelerate the PUT performance so that delay-sensitive applications can benefit from faster content publication.

**Comment by dennis-tra** [comment]
Hey everyone, just wanted to briefly follow up here and ask about the status

**Comment by p4u** [comment]
Now we have some metrics to compare.

We gonna merge this into the development network first, then on stage and finally production.

**Pull request merged**
