### PR TITLE
hotfix disable failing ipfssync test due to upstream issue

### PR DESCRIPTION
**Pull request by altergui**
ExternalIP() is taking too long due to ident.me timing out

### CODE REVIEW

**Comment by p4u** [comment]
Umm, why the tests are failing? it does not look as something related to this PR. @mvdan ?

**Comment by mvdan** [comment]
The tests just seem to be running into the 1m timeout, still.

**Comment by mvdan** [comment]
We could increase the timeout to 2m or 3m, but it still seems like the ipfssync/subpub tests still take too long

**Comment by p4u** [comment]
@altergui ?

**Pull request closed without merging**
