### PR TITLE
bump go v1.20

### PR DESCRIPTION
**Pull request by altergui**
needs bumping go-libp2p and kubo as well

this is blocked by https://github.com/libp2p/go-libp2p/pull/2040 which was merged a few days ago but not yet included in a release, and then likely waiting for kubo to do a release as well

### CODE REVIEW

**Comment by altergui** [comment]
go-libp2p v0.25.1 was released, supporting go 1.20

challenge unlocked :partying_face:

but on a first look at these errors, it seems we need to wait for kubo release as well?

```
# github.com/ipfs/kubo/config
Error: ../../../go/pkg/mod/github.com/ipfs/kubo@v0.18.1/config/swarm.go:145:17: undefined: rcmgr.LimitConfig
# github.com/libp2p/go-libp2p-kad-dht
Error: ../../../go/pkg/mod/github.com/libp2p/go-libp2p-kad-dht@v0.20.0/subscriber_notifee.go:149:52: cannot use dht.protocolsStrs (variable of type []string) as []protocol.ID value in argument to dht.peerstore.FirstSupportedProtocol
# github.com/ipfs/go-bitswap/network
Error: ../../../go/pkg/mod/github.com/ipfs/go-bitswap@v0.11.0/network/ipfs_impl.go:168:21: cannot use generic type multistream.ErrNotSupported without instantiation
# github.com/libp2p/go-libp2p-pubsub
Error: ../../../go/pkg/mod/github.com/libp2p/go-libp2p-pubsub@v0.8.3/pubsub.go:326:32: cannot use ps.protoMatchFunc(string(id)) (value of type func(string) bool) as func(protocol.ID) bool value in argument to h.SetStreamHandlerMatch
# github.com/ipfs/kubo/p2p
Error: ../../../go/pkg/mod/github.com/ipfs/kubo@v0.18.1/p2p/listener.go:44:36: cannot use func(p string) bool {…} (value of type func(p string) bool) as func(protocol.ID) bool value in argument to host.SetStreamHandlerMatch
Error: ../../../go/pkg/mod/github.com/ipfs/kubo@v0.18.1/p2p/p2p.go:47:11: invalid operation: p != proto (mismatched types protocol.ID and string)
```

https://github.com/vocdoni/vocdoni-node/actions/runs/4168785041/jobs/7215986676

**Comment by mvdan** [comment]
Yeah, it appears that libp2p itself had breaking changes, so upstreams like ipfs need to be updated. See https://github.com/ipfs/kubo/pull/9647. Looks like we need to wait for another release.

**Comment by Jorropo** [comment]
I would wait until we release Kubo 0.19.0, first RC should be going out within the next week: https://github.com/ipfs/kubo/issues/9502

**Comment by mvdan** [comment]
Thanks :) I empathize with Marten and having to update quic-go for every Go release. Hopefully that will go away now that https://github.com/golang/go/issues/44886 is gaining traction. It's just unfortunate that we're stuck not being able to use Go 1.20 two weeks after its release, but we can live with 1.19.x for another week for sure.

**Comment by altergui** [comment]
merging this will fix #843

**Comment by altergui** [comment]
this is neverending but i see the light at the end of the tunnel

**Comment by altergui** [comment]
all checks, tests, staticchecks and whatever checks pass now, 
rebased and squashed into a single commit with comprehensible changelog in commit message

**Review by p4u — APPROVED** [review]

**Comment by p4u** [comment]
@altergui we need to fix conflicts

**Pull request merged**
