### PR TITLE
[BREAKING] Dvot 499/f/add delegates logic

### PR DESCRIPTION
**Pull request by jordipainan**
Adds delegates logic on process related txs.

Refactors the process_test.go file for better readability.
Adds more tests to process_test.go.

### CODE REVIEW

**Comment by jordipainan** [comment]
There are 3 breaking PRs, once #653 is merged here, rebase this with master (only if #651 was previously applied to master)

**Comment by p4u** [comment]
Please, rebase with master now that the previous PR is already merged.

**Comment by jordipainan** [comment]
Ready to merge  @p4u

**Review by altergui — APPROVED** [review]
LGTM

i did not *thoroughly* read process_test.go but i did `go test` and it passes.

**Review by p4u — APPROVED** [review]

**Pull request merged**
