### PR TITLE
vochain/indexer: add initial support for backups

### PR DESCRIPTION
**Pull request by mvdan**
(see commit messages - please do not squash)

Updates #1062.

### CODE REVIEW

**Review by altergui — DISMISSED** [review]
LGTM, as always

specially love the idiomatic of indexer.New() and indexer.Options, wish all of our packages were so nice :heart_eyes:

**Comment by mvdan** [comment]
Forgot to update this thread - this needs a bit of a refactor, since a chat with @p4u showed that we need to be able to restore a backup _after_ we have initialized the indexer.

**Comment by p4u** [comment]
Please ping me when this is done @mvdan

**Comment by mvdan** [comment]
@p4u rebased and implemented, PTAL

**Review by p4u — APPROVED** [review]

**Pull request merged**
