### PR TITLE
api: remove non paginated endpoints

### PR DESCRIPTION
**Pull request by altergui**
* /chain/transactions
* /accounts/{organizationID}/elections/status/{status}

these went unnoticed in #842

### CODE REVIEW

**Comment by p4u** [comment]
It might be that apiclient needs some update regarding this (and the previous) change? Can you check it? Thanks!

**Comment by altergui** [comment]
> It might be that apiclient needs some update regarding this (and the previous) change? Can you check it? Thanks!

good one, didn't even think about this. i just double checked and everything looks good, there are no GETs to unpaginated endpoints inside package apiclient

```
$ git grep c.Request apiclient/
apiclient/account.go:31:        resp, code, err := c.Request(HTTPGET, nil, "accounts", "treasurer")
apiclient/account.go:55:        resp, code, err := c.Request(HTTPGET, nil, "accounts", address)
apiclient/account.go:134:       resp, code, err := c.Request(HTTPPOST, &api.AccountSet{
apiclient/account.go:195:       resp, code, err := c.Request(HTTPPOST, &api.AccountSet{
apiclient/account.go:216:       resp, code, err := c.Request(HTTPGET, nil, "accounts", from.Hex(), "transfers", "page", strconv.Itoa(page))
apiclient/blockchain.go:21:     resp, code, err := c.Request(HTTPGET, nil, "chain", "transactions", "cost")
apiclient/blockchain.go:53:     resp, code, err := c.Request(HTTPGET, nil, "chain", "transactions", "reference", txHash.String())
apiclient/blockchain.go:74:     resp, code, err := c.Request(HTTPGET, nil,
apiclient/blockchain.go:89:     resp, code, err := c.Request(HTTPPOST, organizationID, "chain", "organizations", "filter", "page", fmt.Sprintf("%d", page))
apiclient/census.go:44: resp, code, err := c.Request("POST", nil, "censuses", censusType)
apiclient/census.go:65: resp, code, err := c.Request("POST", &participants, "censuses", censusID.String(), "participants")
apiclient/census.go:77: resp, code, err := c.Request("GET", nil, "censuses", censusID.String(), "size")
apiclient/census.go:95: resp, code, err := c.Request("POST", nil, "censuses", censusID.String(), "publish")
apiclient/census.go:112:        resp, code, err := c.Request("GET", nil, "censuses", censusID.String(), "proof", voterKey.String())
apiclient/census.go:143:        resp, code, err := c.Request("GET", nil, "censuses", censusRoot.String(), "proof", c.zkAddr.String())
apiclient/client.go:58: data, status, err := c.Request(HTTPGET, nil, "chain", "info")
apiclient/client.go:122:        data, status, err := c.Request(HTTPGET, nil, "chain", "info")
apiclient/election.go:20:       resp, code, err := c.Request("GET", nil, "elections", electionID.String())
apiclient/election.go:72:       resp, code, err := c.Request("POST", electionCreate, "elections")
apiclient/election.go:246:      resp, code, err := c.Request("POST", electionCreate, "elections")
apiclient/election.go:317:      resp, code, err := c.Request("POST", &api.Transaction{Payload: stx}, "chain", "transactions")
apiclient/election.go:334:      resp, code, err := c.Request("GET", nil, "elections", electionID.String(), "votes", "count")
apiclient/election.go:354:      resp, code, err := c.Request("GET", nil, "elections", electionID.String(), "scrutiny")
apiclient/election.go:385:      resp, code, err := c.Request("POST", body, "elections", "filter", "page", strconv.Itoa(page))
apiclient/helpers.go:25:        resp, code, err := c.Request(HTTPGET, nil, "chain", "info")
apiclient/helpers.go:41:        resp, code, err := c.Request(HTTPGET, nil, "chain", "dateToBlock", fmt.Sprintf("%d", date.Unix()))
apiclient/helpers.go:69:        resp, code, err := c.Request(HTTPPOST, tx, "chain", "transactions")
apiclient/vote.go:134:  resp, code, err := c.Request("POST", voteAPI, "votes")
apiclient/vote.go:151:  resp, code, err := c.Request("GET", nil, "votes", "verify", electionID.String(), voteID.String())
```

(the one in apiclient/blockchain.go:74: is multiline but fetches a single tx by hash
`"chain", "transactions", fmt.Sprintf("%d", ref.Height), fmt.Sprintf("%d", ref.Index)`)

ideally we would be testing this in CI, and in reality we are testing (at least part) of the apiclient (in end2endtest), but without a test coverage profile is hard to say, that's why i'm eager to bump go v1.20 and produce covprofile for binaries.

**Comment by altergui** [comment]
so this is ready to review/merge. docs don't need updating, since this hotfix is making the code actually follow docs :sweat_smile:

**Comment by altergui** [comment]
i love self-updated documentation so much :heart:  #841 

image

**Review by p4u — APPROVED** [review]

**Review by jordipainan — APPROVED** [review]

**Pull request merged**
