### PR TITLE
vochain: use a better LRU

### PR DESCRIPTION
**Pull request by mvdan**
(see commit message)

### CODE REVIEW

**Comment by p4u** [comment]
Looks good. However I think we might have it as a standalone package so other packages can also use it. Maybe `db/lru` ?

**Comment by mvdan** [comment]
Hm, it has little to do with databases though. Since we use LRUs only for the vochain right now, how about `vochain/lru` or `vochain/cache`?

**Comment by mvdan** [comment]
Actually, I take that back - if only the vochain package needs this LRU, then I don't think we should split it into a separate package right now. We should only do that when we need it in the future. Prematurely splitting stuff into more packages is not a good idea.

**Comment by p4u** [comment]
Also scrutinizer uses LRUs https://github.com/vocdoni/vocdoni-node/blob/master/vochain/scrutinizer/scrutinizer.go#L11

**Comment by p4u** [comment]
And I bet we'll need LRU soon on packages such as censustree and statedb

**Comment by mvdan** [comment]
Ah, fair enough - I'll move it under db/lru.

**Comment by mvdan** [comment]
@p4u take a look, it's moved now. If this sounds good, I'll start moving the other LRU uses to this new package, also extending its API as needed.

**Comment by p4u** [comment]
Yes, sounds good.// New creates a new Cache with a given maximum number of entries.
￼

**Comment by mvdan** [comment]
Should we approve and merge, then? I thought I'd do one PR for each of the LRU caches I replace, to keep the changes smaller and easier to review and revert.

**Review by p4u — APPROVED** [review]

**Pull request merged**
