### PR TITLE
anonymous encrypted end2end test

### PR DESCRIPTION
**Pull request by lucasmenendez**

### CODE REVIEW

**Comment by p4u** [comment]
Great! But please add it to the compose start script for the CI testing.

**Comment by p4u** [comment]
> Great! But please add it to the compose start script for the CI testing.

ping @lucasmenendez

**Comment by lucasmenendez** [comment]
I added it to [`dockerfiles/testsuite/start_test.sh`](https://github.com/vocdoni/vocdoni-node/pull/1257/commits/3661c43f2cf8744db7452e7f980adc5c6fb0939a#diff-e8945a31b72a26882ba6176b1c5275b7eaf384a10b68f2bb5ecc02738b3ee1b8), but i cant test it... the miners locks during fast sync :(

**Comment by p4u** [comment]
@lucasmenendez reabase and try again after merging #1264

**Pull request merged**
